-- +goose Up
CREATE TABLE dim_service (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(200) NOT NULL,
  business_id BIGINT UNSIGNED NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_service_code (code),
  FOREIGN KEY (business_id) REFERENCES dim_business(id)
) ENGINE=InnoDB;

CREATE TABLE dim_initiative (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(200) NOT NULL,
  service_id BIGINT UNSIGNED NOT NULL,
  primary_department_id BIGINT UNSIGNED NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_initiative_code (code),
  FOREIGN KEY (service_id) REFERENCES dim_service(id),
  FOREIGN KEY (primary_department_id) REFERENCES dim_department(id)
) ENGINE=InnoDB;

-- +goose Down
DROP TABLE dim_initiative;
DROP TABLE dim_service;
