// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (user_id, action, entity_type, entity_id, detail, ip_address)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	UserID     sql.NullInt64   `json:"user_id"`
	Action     string          `json:"action"`
	EntityType string          `json:"entity_type"`
	EntityID   sql.NullInt64   `json:"entity_id"`
	Detail     json.RawMessage `json:"detail"`
	IpAddress  sql.NullString  `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Detail,
		arg.IpAddress,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.user_id, u.name AS user_name, u.email AS user_email,
       a.action, a.entity_type, a.entity_id, a.detail, a.ip_address, a.created_at
FROM audit_log a
LEFT JOIN app_user u ON u.id = a.user_id
WHERE (? IS NULL OR a.user_id = ?)
  AND (? IS NULL OR a.action = ?)
  AND (? IS NULL OR a.entity_type = ?)
  AND (? IS NULL OR a.created_at >= ?)
  AND (? IS NULL OR a.created_at <= ?)
ORDER BY a.created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsParams struct {
	UserID     sql.NullInt64  `json:"user_id"`
	Action     sql.NullString `json:"action"`
	EntityType sql.NullString `json:"entity_type"`
	FromDate   sql.NullTime   `json:"from_date"`
	ToDate     sql.NullTime   `json:"to_date"`
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
}

type ListAuditLogsRow struct {
	ID         uint64          `json:"id"`
	UserID     sql.NullInt64   `json:"user_id"`
	UserName   sql.NullString  `json:"user_name"`
	UserEmail  sql.NullString  `json:"user_email"`
	Action     string          `json:"action"`
	EntityType string          `json:"entity_type"`
	EntityID   sql.NullInt64   `json:"entity_id"`
	Detail     json.RawMessage `json:"detail"`
	IpAddress  sql.NullString  `json:"ip_address"`
	CreatedAt  time.Time       `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.UserID,
		arg.UserID,
		arg.Action,
		arg.Action,
		arg.EntityType,
		arg.EntityType,
		arg.FromDate,
		arg.FromDate,
		arg.ToDate,
		arg.ToDate,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Detail,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
