// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dimensions.sql

package db

import (
	"context"
	"time"
)

const createAccount = `-- name: CreateAccount :execlastid
INSERT INTO dim_account (code, name, account_type) VALUES (?, ?, ?)
`

type CreateAccountParams struct {
	Code        string                `json:"code"`
	Name        string                `json:"name"`
	AccountType DimAccountAccountType `json:"account_type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAccount, arg.Code, arg.Name, arg.AccountType)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createBusiness = `-- name: CreateBusiness :execlastid
INSERT INTO dim_business (code, name) VALUES (?, ?)
`

type CreateBusinessParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createBusiness, arg.Code, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createDepartment = `-- name: CreateDepartment :execlastid
INSERT INTO dim_department (code, name) VALUES (?, ?)
`

type CreateDepartmentParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDepartment, arg.Code, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createInitiative = `-- name: CreateInitiative :execlastid
INSERT INTO dim_initiative (code, name, project_id, primary_department_id) VALUES (?, ?, ?, ?)
`

type CreateInitiativeParams struct {
	Code                string `json:"code"`
	Name                string `json:"name"`
	ProjectID           uint64 `json:"project_id"`
	PrimaryDepartmentID uint64 `json:"primary_department_id"`
}

func (q *Queries) CreateInitiative(ctx context.Context, arg CreateInitiativeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createInitiative,
		arg.Code,
		arg.Name,
		arg.ProjectID,
		arg.PrimaryDepartmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createProject = `-- name: CreateProject :execlastid
INSERT INTO dim_project (code, name, service_id, primary_department_id) VALUES (?, ?, ?, ?)
`

type CreateProjectParams struct {
	Code                string `json:"code"`
	Name                string `json:"name"`
	ServiceID           uint64 `json:"service_id"`
	PrimaryDepartmentID uint64 `json:"primary_department_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProject,
		arg.Code,
		arg.Name,
		arg.ServiceID,
		arg.PrimaryDepartmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createService = `-- name: CreateService :execlastid
INSERT INTO dim_service (code, name, business_id) VALUES (?, ?, ?)
`

type CreateServiceParams struct {
	Code       string `json:"code"`
	Name       string `json:"name"`
	BusinessID uint64 `json:"business_id"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createService, arg.Code, arg.Name, arg.BusinessID)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, code, name, account_type, is_active, created_at, updated_at
FROM dim_account
ORDER BY code
`

func (q *Queries) ListAccounts(ctx context.Context) ([]DimAccount, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DimAccount
	for rows.Next() {
		var i DimAccount
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinesses = `-- name: ListBusinesses :many
SELECT id, code, name, is_active, created_at, updated_at
FROM dim_business
ORDER BY code
`

func (q *Queries) ListBusinesses(ctx context.Context) ([]DimBusiness, error) {
	rows, err := q.db.QueryContext(ctx, listBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DimBusiness
	for rows.Next() {
		var i DimBusiness
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, code, name, is_active, created_at, updated_at
FROM dim_department
ORDER BY code
`

func (q *Queries) ListDepartments(ctx context.Context) ([]DimDepartment, error) {
	rows, err := q.db.QueryContext(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DimDepartment
	for rows.Next() {
		var i DimDepartment
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInitiatives = `-- name: ListInitiatives :many
SELECT id, code, name, project_id, primary_department_id, is_active, created_at, updated_at
FROM dim_initiative
ORDER BY code
`

type ListInitiativesRow struct {
	ID                  uint64    `json:"id"`
	Code                string    `json:"code"`
	Name                string    `json:"name"`
	ProjectID           uint64    `json:"project_id"`
	PrimaryDepartmentID uint64    `json:"primary_department_id"`
	IsActive            bool      `json:"is_active"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

func (q *Queries) ListInitiatives(ctx context.Context) ([]ListInitiativesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInitiatives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInitiativesRow
	for rows.Next() {
		var i ListInitiativesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ProjectID,
			&i.PrimaryDepartmentID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, code, name, service_id, primary_department_id, is_active, created_at, updated_at
FROM dim_project
ORDER BY code
`

func (q *Queries) ListProjects(ctx context.Context) ([]DimProject, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DimProject
	for rows.Next() {
		var i DimProject
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ServiceID,
			&i.PrimaryDepartmentID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, code, name, business_id, is_active, created_at, updated_at
FROM dim_service
ORDER BY code
`

func (q *Queries) ListServices(ctx context.Context) ([]DimService, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DimService
	for rows.Next() {
		var i DimService
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.BusinessID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE dim_account SET code = ?, name = ?, account_type = ?, is_active = ? WHERE id = ?
`

type UpdateAccountParams struct {
	Code        string                `json:"code"`
	Name        string                `json:"name"`
	AccountType DimAccountAccountType `json:"account_type"`
	IsActive    bool                  `json:"is_active"`
	ID          uint64                `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Code,
		arg.Name,
		arg.AccountType,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateBusiness = `-- name: UpdateBusiness :exec
UPDATE dim_business SET code = ?, name = ?, is_active = ? WHERE id = ?
`

type UpdateBusinessParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	ID       uint64 `json:"id"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) error {
	_, err := q.db.ExecContext(ctx, updateBusiness,
		arg.Code,
		arg.Name,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateDepartment = `-- name: UpdateDepartment :exec
UPDATE dim_department SET code = ?, name = ?, is_active = ? WHERE id = ?
`

type UpdateDepartmentParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	ID       uint64 `json:"id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) error {
	_, err := q.db.ExecContext(ctx, updateDepartment,
		arg.Code,
		arg.Name,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateInitiative = `-- name: UpdateInitiative :exec
UPDATE dim_initiative SET code = ?, name = ?, project_id = ?, primary_department_id = ?, is_active = ? WHERE id = ?
`

type UpdateInitiativeParams struct {
	Code                string `json:"code"`
	Name                string `json:"name"`
	ProjectID           uint64 `json:"project_id"`
	PrimaryDepartmentID uint64 `json:"primary_department_id"`
	IsActive            bool   `json:"is_active"`
	ID                  uint64 `json:"id"`
}

func (q *Queries) UpdateInitiative(ctx context.Context, arg UpdateInitiativeParams) error {
	_, err := q.db.ExecContext(ctx, updateInitiative,
		arg.Code,
		arg.Name,
		arg.ProjectID,
		arg.PrimaryDepartmentID,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE dim_project SET code = ?, name = ?, service_id = ?, primary_department_id = ?, is_active = ? WHERE id = ?
`

type UpdateProjectParams struct {
	Code                string `json:"code"`
	Name                string `json:"name"`
	ServiceID           uint64 `json:"service_id"`
	PrimaryDepartmentID uint64 `json:"primary_department_id"`
	IsActive            bool   `json:"is_active"`
	ID                  uint64 `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.Code,
		arg.Name,
		arg.ServiceID,
		arg.PrimaryDepartmentID,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateService = `-- name: UpdateService :exec
UPDATE dim_service SET code = ?, name = ?, business_id = ?, is_active = ? WHERE id = ?
`

type UpdateServiceParams struct {
	Code       string `json:"code"`
	Name       string `json:"name"`
	BusinessID uint64 `json:"business_id"`
	IsActive   bool   `json:"is_active"`
	ID         uint64 `json:"id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateService,
		arg.Code,
		arg.Name,
		arg.BusinessID,
		arg.IsActive,
		arg.ID,
	)
	return err
}
