// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dimensions.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :execlastid
INSERT INTO dim_account (code, name, account_type) VALUES (?, ?, ?)
`

type CreateAccountParams struct {
	Code        string                `json:"code"`
	Name        string                `json:"name"`
	AccountType DimAccountAccountType `json:"account_type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAccount, arg.Code, arg.Name, arg.AccountType)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createBusiness = `-- name: CreateBusiness :execlastid
INSERT INTO dim_business (code, name) VALUES (?, ?)
`

type CreateBusinessParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createBusiness, arg.Code, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createDepartment = `-- name: CreateDepartment :execlastid
INSERT INTO dim_department (code, name) VALUES (?, ?)
`

type CreateDepartmentParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDepartment, arg.Code, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, code, name, account_type, is_active, created_at, updated_at
FROM dim_account
ORDER BY code
`

func (q *Queries) ListAccounts(ctx context.Context) ([]DimAccount, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DimAccount
	for rows.Next() {
		var i DimAccount
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinesses = `-- name: ListBusinesses :many
SELECT id, code, name, is_active, created_at, updated_at
FROM dim_business
ORDER BY code
`

func (q *Queries) ListBusinesses(ctx context.Context) ([]DimBusiness, error) {
	rows, err := q.db.QueryContext(ctx, listBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DimBusiness
	for rows.Next() {
		var i DimBusiness
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, code, name, is_active, created_at, updated_at
FROM dim_department
ORDER BY code
`

func (q *Queries) ListDepartments(ctx context.Context) ([]DimDepartment, error) {
	rows, err := q.db.QueryContext(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DimDepartment
	for rows.Next() {
		var i DimDepartment
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE dim_account SET code = ?, name = ?, account_type = ?, is_active = ? WHERE id = ?
`

type UpdateAccountParams struct {
	Code        string                `json:"code"`
	Name        string                `json:"name"`
	AccountType DimAccountAccountType `json:"account_type"`
	IsActive    bool                  `json:"is_active"`
	ID          uint64                `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Code,
		arg.Name,
		arg.AccountType,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateBusiness = `-- name: UpdateBusiness :exec
UPDATE dim_business SET code = ?, name = ?, is_active = ? WHERE id = ?
`

type UpdateBusinessParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	ID       uint64 `json:"id"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) error {
	_, err := q.db.ExecContext(ctx, updateBusiness,
		arg.Code,
		arg.Name,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateDepartment = `-- name: UpdateDepartment :exec
UPDATE dim_department SET code = ?, name = ?, is_active = ? WHERE id = ?
`

type UpdateDepartmentParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	ID       uint64 `json:"id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) error {
	_, err := q.db.ExecContext(ctx, updateDepartment,
		arg.Code,
		arg.Name,
		arg.IsActive,
		arg.ID,
	)
	return err
}
