// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package db

import (
	"context"
	"database/sql"
)

const listFactAmountsByScenarioVersion = `-- name: ListFactAmountsByScenarioVersion :many
SELECT business_id, department_id, account_id, period_id, amount
FROM fact_amount
WHERE scenario_version_id = ?
`

type ListFactAmountsByScenarioVersionRow struct {
	BusinessID   uint64 `json:"business_id"`
	DepartmentID uint64 `json:"department_id"`
	AccountID    uint64 `json:"account_id"`
	PeriodID     uint64 `json:"period_id"`
	Amount       string `json:"amount"`
}

func (q *Queries) ListFactAmountsByScenarioVersion(ctx context.Context, scenarioVersionID uint64) ([]ListFactAmountsByScenarioVersionRow, error) {
	rows, err := q.db.QueryContext(ctx, listFactAmountsByScenarioVersion, scenarioVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactAmountsByScenarioVersionRow
	for rows.Next() {
		var i ListFactAmountsByScenarioVersionRow
		if err := rows.Scan(
			&i.BusinessID,
			&i.DepartmentID,
			&i.AccountID,
			&i.PeriodID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFactAmount = `-- name: UpsertFactAmount :exec
INSERT INTO fact_amount (scenario_version_id, business_id, department_id, account_id, period_id, amount, source_type, created_by)
VALUES (?, ?, ?, ?, ?, ?, 'manual_entry', ?)
ON DUPLICATE KEY UPDATE
  amount = VALUES(amount),
  source_type = VALUES(source_type),
  submission_id = NULL,
  import_batch_id = NULL,
  created_by = VALUES(created_by),
  updated_at = CURRENT_TIMESTAMP
`

type UpsertFactAmountParams struct {
	ScenarioVersionID uint64 `json:"scenario_version_id"`
	BusinessID        uint64 `json:"business_id"`
	DepartmentID      uint64 `json:"department_id"`
	AccountID         uint64 `json:"account_id"`
	PeriodID          uint64 `json:"period_id"`
	Amount            string `json:"amount"`
	CreatedBy         uint64 `json:"created_by"`
}

func (q *Queries) UpsertFactAmount(ctx context.Context, arg UpsertFactAmountParams) error {
	_, err := q.db.ExecContext(ctx, upsertFactAmount,
		arg.ScenarioVersionID,
		arg.BusinessID,
		arg.DepartmentID,
		arg.AccountID,
		arg.PeriodID,
		arg.Amount,
		arg.CreatedBy,
	)
	return err
}

const upsertFactAmountFromImport = `-- name: UpsertFactAmountFromImport :exec
INSERT INTO fact_amount (scenario_version_id, business_id, department_id, account_id, period_id, amount, source_type, import_batch_id, created_by)
VALUES (?, ?, ?, ?, ?, ?, 'csv_import', ?, ?)
ON DUPLICATE KEY UPDATE
  amount = VALUES(amount),
  source_type = VALUES(source_type),
  import_batch_id = VALUES(import_batch_id),
  submission_id = NULL,
  created_by = VALUES(created_by),
  updated_at = CURRENT_TIMESTAMP
`

type UpsertFactAmountFromImportParams struct {
	ScenarioVersionID uint64        `json:"scenario_version_id"`
	BusinessID        uint64        `json:"business_id"`
	DepartmentID      uint64        `json:"department_id"`
	AccountID         uint64        `json:"account_id"`
	PeriodID          uint64        `json:"period_id"`
	Amount            string        `json:"amount"`
	ImportBatchID     sql.NullInt64 `json:"import_batch_id"`
	CreatedBy         uint64        `json:"created_by"`
}

func (q *Queries) UpsertFactAmountFromImport(ctx context.Context, arg UpsertFactAmountFromImportParams) error {
	_, err := q.db.ExecContext(ctx, upsertFactAmountFromImport,
		arg.ScenarioVersionID,
		arg.BusinessID,
		arg.DepartmentID,
		arg.AccountID,
		arg.PeriodID,
		arg.Amount,
		arg.ImportBatchID,
		arg.CreatedBy,
	)
	return err
}

const upsertFactAmountFromSubmission = `-- name: UpsertFactAmountFromSubmission :exec
INSERT INTO fact_amount (scenario_version_id, business_id, department_id, account_id, period_id, amount, source_type, submission_id, created_by)
VALUES (?, ?, ?, ?, ?, ?, 'sheet_binding', ?, ?)
ON DUPLICATE KEY UPDATE
  amount = VALUES(amount),
  source_type = VALUES(source_type),
  submission_id = VALUES(submission_id),
  import_batch_id = NULL,
  created_by = VALUES(created_by),
  updated_at = CURRENT_TIMESTAMP
`

type UpsertFactAmountFromSubmissionParams struct {
	ScenarioVersionID uint64        `json:"scenario_version_id"`
	BusinessID        uint64        `json:"business_id"`
	DepartmentID      uint64        `json:"department_id"`
	AccountID         uint64        `json:"account_id"`
	PeriodID          uint64        `json:"period_id"`
	Amount            string        `json:"amount"`
	SubmissionID      sql.NullInt64 `json:"submission_id"`
	CreatedBy         uint64        `json:"created_by"`
}

func (q *Queries) UpsertFactAmountFromSubmission(ctx context.Context, arg UpsertFactAmountFromSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, upsertFactAmountFromSubmission,
		arg.ScenarioVersionID,
		arg.BusinessID,
		arg.DepartmentID,
		arg.AccountID,
		arg.PeriodID,
		arg.Amount,
		arg.SubmissionID,
		arg.CreatedBy,
	)
	return err
}
