// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_batches.sql

package db

import (
	"context"
	"encoding/json"
)

const completeImportBatch = `-- name: CompleteImportBatch :exec
UPDATE import_batch
SET status = ?, row_count = ?, error_count = ?, error_detail = ?, completed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type CompleteImportBatchParams struct {
	Status      ImportBatchStatus `json:"status"`
	RowCount    int32             `json:"row_count"`
	ErrorCount  int32             `json:"error_count"`
	ErrorDetail json.RawMessage   `json:"error_detail"`
	ID          uint64            `json:"id"`
}

func (q *Queries) CompleteImportBatch(ctx context.Context, arg CompleteImportBatchParams) error {
	_, err := q.db.ExecContext(ctx, completeImportBatch,
		arg.Status,
		arg.RowCount,
		arg.ErrorCount,
		arg.ErrorDetail,
		arg.ID,
	)
	return err
}

const createImportBatch = `-- name: CreateImportBatch :execlastid
INSERT INTO import_batch (uploaded_by, original_filename, file_size_bytes, scenario_version_id, status)
VALUES (?, ?, ?, ?, 'processing')
`

type CreateImportBatchParams struct {
	UploadedBy        uint64 `json:"uploaded_by"`
	OriginalFilename  string `json:"original_filename"`
	FileSizeBytes     int32  `json:"file_size_bytes"`
	ScenarioVersionID uint64 `json:"scenario_version_id"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createImportBatch,
		arg.UploadedBy,
		arg.OriginalFilename,
		arg.FileSizeBytes,
		arg.ScenarioVersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listImportBatchesByScenarioVersion = `-- name: ListImportBatchesByScenarioVersion :many
SELECT id, uploaded_by, original_filename, file_size_bytes, scenario_version_id,
       status, row_count, error_count, error_detail, created_at, completed_at
FROM import_batch
WHERE scenario_version_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListImportBatchesByScenarioVersion(ctx context.Context, scenarioVersionID uint64) ([]ImportBatch, error) {
	rows, err := q.db.QueryContext(ctx, listImportBatchesByScenarioVersion, scenarioVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportBatch
	for rows.Next() {
		var i ImportBatch
		if err := rows.Scan(
			&i.ID,
			&i.UploadedBy,
			&i.OriginalFilename,
			&i.FileSizeBytes,
			&i.ScenarioVersionID,
			&i.Status,
			&i.RowCount,
			&i.ErrorCount,
			&i.ErrorDetail,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
