// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: input_bindings.sql

package db

import (
	"context"
	"encoding/json"
)

const createInputBinding = `-- name: CreateInputBinding :execlastid
INSERT INTO input_binding (
  input_sheet_id, name, range_sheet_name,
  start_row, end_row, start_col, end_col,
  header_rows, header_cols,
  row_axis_dimension, col_axis_dimension,
  fixed_dimensions, created_by
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateInputBindingParams struct {
	InputSheetID     uint64                       `json:"input_sheet_id"`
	Name             string                       `json:"name"`
	RangeSheetName   string                       `json:"range_sheet_name"`
	StartRow         int32                        `json:"start_row"`
	EndRow           int32                        `json:"end_row"`
	StartCol         int32                        `json:"start_col"`
	EndCol           int32                        `json:"end_col"`
	HeaderRows       int8                         `json:"header_rows"`
	HeaderCols       int8                         `json:"header_cols"`
	RowAxisDimension InputBindingRowAxisDimension `json:"row_axis_dimension"`
	ColAxisDimension InputBindingColAxisDimension `json:"col_axis_dimension"`
	FixedDimensions  json.RawMessage              `json:"fixed_dimensions"`
	CreatedBy        uint64                       `json:"created_by"`
}

func (q *Queries) CreateInputBinding(ctx context.Context, arg CreateInputBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createInputBinding,
		arg.InputSheetID,
		arg.Name,
		arg.RangeSheetName,
		arg.StartRow,
		arg.EndRow,
		arg.StartCol,
		arg.EndCol,
		arg.HeaderRows,
		arg.HeaderCols,
		arg.RowAxisDimension,
		arg.ColAxisDimension,
		arg.FixedDimensions,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createInputBindingAxisLabel = `-- name: CreateInputBindingAxisLabel :exec
INSERT INTO input_binding_axis_label (
  binding_id, axis, axis_index, raw_label_text,
  resolved_dimension_type, resolved_dimension_id
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateInputBindingAxisLabelParams struct {
	BindingID             uint64                                     `json:"binding_id"`
	Axis                  InputBindingAxisLabelAxis                  `json:"axis"`
	AxisIndex             int32                                      `json:"axis_index"`
	RawLabelText          string                                     `json:"raw_label_text"`
	ResolvedDimensionType InputBindingAxisLabelResolvedDimensionType `json:"resolved_dimension_type"`
	ResolvedDimensionID   uint64                                     `json:"resolved_dimension_id"`
}

func (q *Queries) CreateInputBindingAxisLabel(ctx context.Context, arg CreateInputBindingAxisLabelParams) error {
	_, err := q.db.ExecContext(ctx, createInputBindingAxisLabel,
		arg.BindingID,
		arg.Axis,
		arg.AxisIndex,
		arg.RawLabelText,
		arg.ResolvedDimensionType,
		arg.ResolvedDimensionID,
	)
	return err
}

const getInputBinding = `-- name: GetInputBinding :one
SELECT id, input_sheet_id, name, range_sheet_name,
       start_row, end_row, start_col, end_col,
       header_rows, header_cols,
       row_axis_dimension, col_axis_dimension,
       fixed_dimensions, is_active, created_by, created_at, updated_at
FROM input_binding
WHERE id = ?
`

func (q *Queries) GetInputBinding(ctx context.Context, id uint64) (InputBinding, error) {
	row := q.db.QueryRowContext(ctx, getInputBinding, id)
	var i InputBinding
	err := row.Scan(
		&i.ID,
		&i.InputSheetID,
		&i.Name,
		&i.RangeSheetName,
		&i.StartRow,
		&i.EndRow,
		&i.StartCol,
		&i.EndCol,
		&i.HeaderRows,
		&i.HeaderCols,
		&i.RowAxisDimension,
		&i.ColAxisDimension,
		&i.FixedDimensions,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAxisLabelsByBinding = `-- name: ListAxisLabelsByBinding :many
SELECT id, binding_id, axis, axis_index, raw_label_text,
       resolved_dimension_type, resolved_dimension_id
FROM input_binding_axis_label
WHERE binding_id = ?
ORDER BY axis, axis_index
`

func (q *Queries) ListAxisLabelsByBinding(ctx context.Context, bindingID uint64) ([]InputBindingAxisLabel, error) {
	rows, err := q.db.QueryContext(ctx, listAxisLabelsByBinding, bindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InputBindingAxisLabel
	for rows.Next() {
		var i InputBindingAxisLabel
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.Axis,
			&i.AxisIndex,
			&i.RawLabelText,
			&i.ResolvedDimensionType,
			&i.ResolvedDimensionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInputBindingsBySheet = `-- name: ListInputBindingsBySheet :many
SELECT id, input_sheet_id, name, range_sheet_name,
       start_row, end_row, start_col, end_col,
       header_rows, header_cols,
       row_axis_dimension, col_axis_dimension,
       fixed_dimensions, is_active, created_by, created_at, updated_at
FROM input_binding
WHERE input_sheet_id = ? AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListInputBindingsBySheet(ctx context.Context, inputSheetID uint64) ([]InputBinding, error) {
	rows, err := q.db.QueryContext(ctx, listInputBindingsBySheet, inputSheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InputBinding
	for rows.Next() {
		var i InputBinding
		if err := rows.Scan(
			&i.ID,
			&i.InputSheetID,
			&i.Name,
			&i.RangeSheetName,
			&i.StartRow,
			&i.EndRow,
			&i.StartCol,
			&i.EndCol,
			&i.HeaderRows,
			&i.HeaderCols,
			&i.RowAxisDimension,
			&i.ColAxisDimension,
			&i.FixedDimensions,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
