// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: input_sheets.sql

package db

import (
	"context"
	"time"
)

const createInputSheet = `-- name: CreateInputSheet :execlastid
INSERT INTO input_sheet (owner_user_id, name, sheet_snapshot)
VALUES (?, ?, ?)
`

type CreateInputSheetParams struct {
	OwnerUserID   uint64 `json:"owner_user_id"`
	Name          string `json:"name"`
	SheetSnapshot string `json:"sheet_snapshot"`
}

func (q *Queries) CreateInputSheet(ctx context.Context, arg CreateInputSheetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createInputSheet, arg.OwnerUserID, arg.Name, arg.SheetSnapshot)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getInputSheet = `-- name: GetInputSheet :one
SELECT id, owner_user_id, name, sheet_snapshot, created_at, updated_at
FROM input_sheet
WHERE id = ?
`

func (q *Queries) GetInputSheet(ctx context.Context, id uint64) (InputSheet, error) {
	row := q.db.QueryRowContext(ctx, getInputSheet, id)
	var i InputSheet
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.SheetSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInputSheetsByOwner = `-- name: ListInputSheetsByOwner :many
SELECT id, owner_user_id, name, created_at, updated_at
FROM input_sheet
WHERE owner_user_id = ?
ORDER BY updated_at DESC
`

type ListInputSheetsByOwnerRow struct {
	ID          uint64    `json:"id"`
	OwnerUserID uint64    `json:"owner_user_id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListInputSheetsByOwner(ctx context.Context, ownerUserID uint64) ([]ListInputSheetsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listInputSheetsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInputSheetsByOwnerRow
	for rows.Next() {
		var i ListInputSheetsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInputSheetSnapshot = `-- name: UpdateInputSheetSnapshot :exec
UPDATE input_sheet
SET sheet_snapshot = ?
WHERE id = ? AND owner_user_id = ?
`

type UpdateInputSheetSnapshotParams struct {
	SheetSnapshot string `json:"sheet_snapshot"`
	ID            uint64 `json:"id"`
	OwnerUserID   uint64 `json:"owner_user_id"`
}

func (q *Queries) UpdateInputSheetSnapshot(ctx context.Context, arg UpdateInputSheetSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, updateInputSheetSnapshot, arg.SheetSnapshot, arg.ID, arg.OwnerUserID)
	return err
}
