// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AppUserRole string

const (
	AppUserRoleFieldUser   AppUserRole = "field_user"
	AppUserRoleOfficeAdmin AppUserRole = "office_admin"
)

func (e *AppUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppUserRole(s)
	case string:
		*e = AppUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppUserRole: %T", src)
	}
	return nil
}

type NullAppUserRole struct {
	AppUserRole AppUserRole `json:"app_user_role"`
	Valid       bool        `json:"valid"` // Valid is true if AppUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppUserRole), nil
}

type AppUser struct {
	ID           uint64      `json:"id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Role         AppUserRole `json:"role"`
	PasswordHash string      `json:"password_hash"`
	IsActive     bool        `json:"is_active"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type UserSession struct {
	TokenHash  string         `json:"token_hash"`
	UserID     uint64         `json:"user_id"`
	CreatedAt  time.Time      `json:"created_at"`
	ExpiresAt  time.Time      `json:"expires_at"`
	LastSeenAt time.Time      `json:"last_seen_at"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
}
