// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type AppUserRole string

const (
	AppUserRoleFieldUser   AppUserRole = "field_user"
	AppUserRoleOfficeAdmin AppUserRole = "office_admin"
)

func (e *AppUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppUserRole(s)
	case string:
		*e = AppUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppUserRole: %T", src)
	}
	return nil
}

type NullAppUserRole struct {
	AppUserRole AppUserRole `json:"app_user_role"`
	Valid       bool        `json:"valid"` // Valid is true if AppUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppUserRole), nil
}

type DimAccountAccountType string

const (
	DimAccountAccountTypeRevenue DimAccountAccountType = "revenue"
	DimAccountAccountTypeCost    DimAccountAccountType = "cost"
	DimAccountAccountTypeOther   DimAccountAccountType = "other"
)

func (e *DimAccountAccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DimAccountAccountType(s)
	case string:
		*e = DimAccountAccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for DimAccountAccountType: %T", src)
	}
	return nil
}

type NullDimAccountAccountType struct {
	DimAccountAccountType DimAccountAccountType `json:"dim_account_account_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if DimAccountAccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDimAccountAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.DimAccountAccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DimAccountAccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDimAccountAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DimAccountAccountType), nil
}

type FactAmountSourceType string

const (
	FactAmountSourceTypeManualEntry  FactAmountSourceType = "manual_entry"
	FactAmountSourceTypeSheetBinding FactAmountSourceType = "sheet_binding"
	FactAmountSourceTypeCsvImport    FactAmountSourceType = "csv_import"
)

func (e *FactAmountSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FactAmountSourceType(s)
	case string:
		*e = FactAmountSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for FactAmountSourceType: %T", src)
	}
	return nil
}

type NullFactAmountSourceType struct {
	FactAmountSourceType FactAmountSourceType `json:"fact_amount_source_type"`
	Valid                bool                 `json:"valid"` // Valid is true if FactAmountSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFactAmountSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.FactAmountSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FactAmountSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFactAmountSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FactAmountSourceType), nil
}

type ImportBatchStatus string

const (
	ImportBatchStatusProcessing ImportBatchStatus = "processing"
	ImportBatchStatusCompleted  ImportBatchStatus = "completed"
	ImportBatchStatusFailed     ImportBatchStatus = "failed"
)

func (e *ImportBatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportBatchStatus(s)
	case string:
		*e = ImportBatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportBatchStatus: %T", src)
	}
	return nil
}

type NullImportBatchStatus struct {
	ImportBatchStatus ImportBatchStatus `json:"import_batch_status"`
	Valid             bool              `json:"valid"` // Valid is true if ImportBatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportBatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportBatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportBatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportBatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportBatchStatus), nil
}

type InputBindingAxisLabelAxis string

const (
	InputBindingAxisLabelAxisRow InputBindingAxisLabelAxis = "row"
	InputBindingAxisLabelAxisCol InputBindingAxisLabelAxis = "col"
)

func (e *InputBindingAxisLabelAxis) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InputBindingAxisLabelAxis(s)
	case string:
		*e = InputBindingAxisLabelAxis(s)
	default:
		return fmt.Errorf("unsupported scan type for InputBindingAxisLabelAxis: %T", src)
	}
	return nil
}

type NullInputBindingAxisLabelAxis struct {
	InputBindingAxisLabelAxis InputBindingAxisLabelAxis `json:"input_binding_axis_label_axis"`
	Valid                     bool                      `json:"valid"` // Valid is true if InputBindingAxisLabelAxis is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInputBindingAxisLabelAxis) Scan(value interface{}) error {
	if value == nil {
		ns.InputBindingAxisLabelAxis, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InputBindingAxisLabelAxis.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInputBindingAxisLabelAxis) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InputBindingAxisLabelAxis), nil
}

type InputBindingAxisLabelResolvedDimensionType string

const (
	InputBindingAxisLabelResolvedDimensionTypeAccount    InputBindingAxisLabelResolvedDimensionType = "account"
	InputBindingAxisLabelResolvedDimensionTypePeriod     InputBindingAxisLabelResolvedDimensionType = "period"
	InputBindingAxisLabelResolvedDimensionTypeBusiness   InputBindingAxisLabelResolvedDimensionType = "business"
	InputBindingAxisLabelResolvedDimensionTypeDepartment InputBindingAxisLabelResolvedDimensionType = "department"
)

func (e *InputBindingAxisLabelResolvedDimensionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InputBindingAxisLabelResolvedDimensionType(s)
	case string:
		*e = InputBindingAxisLabelResolvedDimensionType(s)
	default:
		return fmt.Errorf("unsupported scan type for InputBindingAxisLabelResolvedDimensionType: %T", src)
	}
	return nil
}

type NullInputBindingAxisLabelResolvedDimensionType struct {
	InputBindingAxisLabelResolvedDimensionType InputBindingAxisLabelResolvedDimensionType `json:"input_binding_axis_label_resolved_dimension_type"`
	Valid                                      bool                                       `json:"valid"` // Valid is true if InputBindingAxisLabelResolvedDimensionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInputBindingAxisLabelResolvedDimensionType) Scan(value interface{}) error {
	if value == nil {
		ns.InputBindingAxisLabelResolvedDimensionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InputBindingAxisLabelResolvedDimensionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInputBindingAxisLabelResolvedDimensionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InputBindingAxisLabelResolvedDimensionType), nil
}

type InputBindingColAxisDimension string

const (
	InputBindingColAxisDimensionAccount    InputBindingColAxisDimension = "account"
	InputBindingColAxisDimensionPeriod     InputBindingColAxisDimension = "period"
	InputBindingColAxisDimensionBusiness   InputBindingColAxisDimension = "business"
	InputBindingColAxisDimensionDepartment InputBindingColAxisDimension = "department"
	InputBindingColAxisDimensionNone       InputBindingColAxisDimension = "none"
)

func (e *InputBindingColAxisDimension) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InputBindingColAxisDimension(s)
	case string:
		*e = InputBindingColAxisDimension(s)
	default:
		return fmt.Errorf("unsupported scan type for InputBindingColAxisDimension: %T", src)
	}
	return nil
}

type NullInputBindingColAxisDimension struct {
	InputBindingColAxisDimension InputBindingColAxisDimension `json:"input_binding_col_axis_dimension"`
	Valid                        bool                         `json:"valid"` // Valid is true if InputBindingColAxisDimension is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInputBindingColAxisDimension) Scan(value interface{}) error {
	if value == nil {
		ns.InputBindingColAxisDimension, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InputBindingColAxisDimension.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInputBindingColAxisDimension) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InputBindingColAxisDimension), nil
}

type InputBindingRowAxisDimension string

const (
	InputBindingRowAxisDimensionAccount    InputBindingRowAxisDimension = "account"
	InputBindingRowAxisDimensionPeriod     InputBindingRowAxisDimension = "period"
	InputBindingRowAxisDimensionBusiness   InputBindingRowAxisDimension = "business"
	InputBindingRowAxisDimensionDepartment InputBindingRowAxisDimension = "department"
	InputBindingRowAxisDimensionNone       InputBindingRowAxisDimension = "none"
)

func (e *InputBindingRowAxisDimension) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InputBindingRowAxisDimension(s)
	case string:
		*e = InputBindingRowAxisDimension(s)
	default:
		return fmt.Errorf("unsupported scan type for InputBindingRowAxisDimension: %T", src)
	}
	return nil
}

type NullInputBindingRowAxisDimension struct {
	InputBindingRowAxisDimension InputBindingRowAxisDimension `json:"input_binding_row_axis_dimension"`
	Valid                        bool                         `json:"valid"` // Valid is true if InputBindingRowAxisDimension is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInputBindingRowAxisDimension) Scan(value interface{}) error {
	if value == nil {
		ns.InputBindingRowAxisDimension, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InputBindingRowAxisDimension.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInputBindingRowAxisDimension) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InputBindingRowAxisDimension), nil
}

type ScenarioVersionScenarioType string

const (
	ScenarioVersionScenarioTypeBudget   ScenarioVersionScenarioType = "budget"
	ScenarioVersionScenarioTypeForecast ScenarioVersionScenarioType = "forecast"
	ScenarioVersionScenarioTypeActual   ScenarioVersionScenarioType = "actual"
)

func (e *ScenarioVersionScenarioType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScenarioVersionScenarioType(s)
	case string:
		*e = ScenarioVersionScenarioType(s)
	default:
		return fmt.Errorf("unsupported scan type for ScenarioVersionScenarioType: %T", src)
	}
	return nil
}

type NullScenarioVersionScenarioType struct {
	ScenarioVersionScenarioType ScenarioVersionScenarioType `json:"scenario_version_scenario_type"`
	Valid                       bool                        `json:"valid"` // Valid is true if ScenarioVersionScenarioType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScenarioVersionScenarioType) Scan(value interface{}) error {
	if value == nil {
		ns.ScenarioVersionScenarioType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScenarioVersionScenarioType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScenarioVersionScenarioType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScenarioVersionScenarioType), nil
}

type ScenarioVersionStatus string

const (
	ScenarioVersionStatusDraft     ScenarioVersionStatus = "draft"
	ScenarioVersionStatusSubmitted ScenarioVersionStatus = "submitted"
	ScenarioVersionStatusLocked    ScenarioVersionStatus = "locked"
)

func (e *ScenarioVersionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScenarioVersionStatus(s)
	case string:
		*e = ScenarioVersionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScenarioVersionStatus: %T", src)
	}
	return nil
}

type NullScenarioVersionStatus struct {
	ScenarioVersionStatus ScenarioVersionStatus `json:"scenario_version_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if ScenarioVersionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScenarioVersionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScenarioVersionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScenarioVersionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScenarioVersionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScenarioVersionStatus), nil
}

type SubmissionStatus string

const (
	SubmissionStatusDraft      SubmissionStatus = "draft"
	SubmissionStatusSubmitted  SubmissionStatus = "submitted"
	SubmissionStatusSuperseded SubmissionStatus = "superseded"
)

func (e *SubmissionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionStatus(s)
	case string:
		*e = SubmissionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionStatus: %T", src)
	}
	return nil
}

type NullSubmissionStatus struct {
	SubmissionStatus SubmissionStatus `json:"submission_status"`
	Valid            bool             `json:"valid"` // Valid is true if SubmissionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionStatus), nil
}

type SubmissionValidationStatus string

const (
	SubmissionValidationStatusOk      SubmissionValidationStatus = "ok"
	SubmissionValidationStatusWarning SubmissionValidationStatus = "warning"
	SubmissionValidationStatusError   SubmissionValidationStatus = "error"
)

func (e *SubmissionValidationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionValidationStatus(s)
	case string:
		*e = SubmissionValidationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionValidationStatus: %T", src)
	}
	return nil
}

type NullSubmissionValidationStatus struct {
	SubmissionValidationStatus SubmissionValidationStatus `json:"submission_validation_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if SubmissionValidationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionValidationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionValidationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionValidationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionValidationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionValidationStatus), nil
}

type AppUser struct {
	ID           uint64      `json:"id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Role         AppUserRole `json:"role"`
	PasswordHash string      `json:"password_hash"`
	IsActive     bool        `json:"is_active"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type AuditLog struct {
	ID         uint64          `json:"id"`
	UserID     sql.NullInt64   `json:"user_id"`
	Action     string          `json:"action"`
	EntityType string          `json:"entity_type"`
	EntityID   sql.NullInt64   `json:"entity_id"`
	Detail     json.RawMessage `json:"detail"`
	IpAddress  sql.NullString  `json:"ip_address"`
	CreatedAt  time.Time       `json:"created_at"`
}

type DimAccount struct {
	ID          uint64                `json:"id"`
	Code        string                `json:"code"`
	Name        string                `json:"name"`
	AccountType DimAccountAccountType `json:"account_type"`
	IsActive    bool                  `json:"is_active"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type DimBusiness struct {
	ID        uint64    `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DimDepartment struct {
	ID        uint64    `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DimPeriod struct {
	ID            uint64    `json:"id"`
	FiscalYear    int16     `json:"fiscal_year"`
	FiscalMonth   int8      `json:"fiscal_month"`
	CalendarYear  int16     `json:"calendar_year"`
	CalendarMonth int8      `json:"calendar_month"`
	StartDate     time.Time `json:"start_date"`
	EndDate       time.Time `json:"end_date"`
	Label         string    `json:"label"`
}

type FactAmount struct {
	ID                uint64               `json:"id"`
	ScenarioVersionID uint64               `json:"scenario_version_id"`
	BusinessID        uint64               `json:"business_id"`
	DepartmentID      uint64               `json:"department_id"`
	AccountID         uint64               `json:"account_id"`
	PeriodID          uint64               `json:"period_id"`
	Amount            string               `json:"amount"`
	SourceType        FactAmountSourceType `json:"source_type"`
	SubmissionID      sql.NullInt64        `json:"submission_id"`
	ImportBatchID     sql.NullInt64        `json:"import_batch_id"`
	CreatedBy         uint64               `json:"created_by"`
	CreatedAt         time.Time            `json:"created_at"`
	UpdatedAt         time.Time            `json:"updated_at"`
}

type ImportBatch struct {
	ID                uint64            `json:"id"`
	UploadedBy        uint64            `json:"uploaded_by"`
	OriginalFilename  string            `json:"original_filename"`
	FileSizeBytes     int32             `json:"file_size_bytes"`
	ScenarioVersionID uint64            `json:"scenario_version_id"`
	Status            ImportBatchStatus `json:"status"`
	RowCount          int32             `json:"row_count"`
	ErrorCount        int32             `json:"error_count"`
	ErrorDetail       json.RawMessage   `json:"error_detail"`
	CreatedAt         time.Time         `json:"created_at"`
	CompletedAt       sql.NullTime      `json:"completed_at"`
}

type InputBinding struct {
	ID               uint64                       `json:"id"`
	InputSheetID     uint64                       `json:"input_sheet_id"`
	Name             string                       `json:"name"`
	RangeSheetName   string                       `json:"range_sheet_name"`
	StartRow         int32                        `json:"start_row"`
	EndRow           int32                        `json:"end_row"`
	StartCol         int32                        `json:"start_col"`
	EndCol           int32                        `json:"end_col"`
	HeaderRows       int8                         `json:"header_rows"`
	HeaderCols       int8                         `json:"header_cols"`
	RowAxisDimension InputBindingRowAxisDimension `json:"row_axis_dimension"`
	ColAxisDimension InputBindingColAxisDimension `json:"col_axis_dimension"`
	FixedDimensions  json.RawMessage              `json:"fixed_dimensions"`
	IsActive         bool                         `json:"is_active"`
	CreatedBy        uint64                       `json:"created_by"`
	CreatedAt        time.Time                    `json:"created_at"`
	UpdatedAt        time.Time                    `json:"updated_at"`
}

type InputBindingAxisLabel struct {
	ID                    uint64                                     `json:"id"`
	BindingID             uint64                                     `json:"binding_id"`
	Axis                  InputBindingAxisLabelAxis                  `json:"axis"`
	AxisIndex             int32                                      `json:"axis_index"`
	RawLabelText          string                                     `json:"raw_label_text"`
	ResolvedDimensionType InputBindingAxisLabelResolvedDimensionType `json:"resolved_dimension_type"`
	ResolvedDimensionID   uint64                                     `json:"resolved_dimension_id"`
}

type InputSheet struct {
	ID            uint64    `json:"id"`
	OwnerUserID   uint64    `json:"owner_user_id"`
	Name          string    `json:"name"`
	SheetSnapshot string    `json:"sheet_snapshot"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ScenarioVersion struct {
	ID           uint64                      `json:"id"`
	ScenarioType ScenarioVersionScenarioType `json:"scenario_type"`
	FiscalYear   int16                       `json:"fiscal_year"`
	AsOfPeriodID sql.NullInt64               `json:"as_of_period_id"`
	VersionLabel string                      `json:"version_label"`
	Status       ScenarioVersionStatus       `json:"status"`
	IsCurrent    bool                        `json:"is_current"`
	CreatedBy    uint64                      `json:"created_by"`
	CreatedAt    time.Time                   `json:"created_at"`
	SubmittedAt  sql.NullTime                `json:"submitted_at"`
	LockedAt     sql.NullTime                `json:"locked_at"`
}

type Submission struct {
	ID                uint64                     `json:"id"`
	InputSheetID      uint64                     `json:"input_sheet_id"`
	BindingID         uint64                     `json:"binding_id"`
	ScenarioVersionID uint64                     `json:"scenario_version_id"`
	SubmittedBy       uint64                     `json:"submitted_by"`
	SubmittedAt       time.Time                  `json:"submitted_at"`
	Status            SubmissionStatus           `json:"status"`
	ValidationStatus  SubmissionValidationStatus `json:"validation_status"`
	ValidationDetail  json.RawMessage            `json:"validation_detail"`
}

type SubmissionScope struct {
	SubmissionID uint64 `json:"submission_id"`
	BusinessID   uint64 `json:"business_id"`
	DepartmentID uint64 `json:"department_id"`
}

type UserAssignment struct {
	ID           uint64 `json:"id"`
	UserID       uint64 `json:"user_id"`
	BusinessID   uint64 `json:"business_id"`
	DepartmentID uint64 `json:"department_id"`
	IsActive     bool   `json:"is_active"`
}

type UserSession struct {
	TokenHash  string         `json:"token_hash"`
	UserID     uint64         `json:"user_id"`
	CreatedAt  time.Time      `json:"created_at"`
	ExpiresAt  time.Time      `json:"expires_at"`
	LastSeenAt time.Time      `json:"last_seen_at"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
}
