// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: periods.sql

package db

import (
	"context"
	"time"
)

const listPeriods = `-- name: ListPeriods :many
SELECT id, fiscal_year, fiscal_month, calendar_year, calendar_month, start_date, end_date, label
FROM dim_period
ORDER BY fiscal_year, fiscal_month
`

func (q *Queries) ListPeriods(ctx context.Context) ([]DimPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DimPeriod
	for rows.Next() {
		var i DimPeriod
		if err := rows.Scan(
			&i.ID,
			&i.FiscalYear,
			&i.FiscalMonth,
			&i.CalendarYear,
			&i.CalendarMonth,
			&i.StartDate,
			&i.EndDate,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPeriod = `-- name: UpsertPeriod :exec
INSERT INTO dim_period (fiscal_year, fiscal_month, calendar_year, calendar_month, start_date, end_date, label)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  calendar_year = VALUES(calendar_year),
  calendar_month = VALUES(calendar_month),
  start_date = VALUES(start_date),
  end_date = VALUES(end_date),
  label = VALUES(label)
`

type UpsertPeriodParams struct {
	FiscalYear    int16     `json:"fiscal_year"`
	FiscalMonth   int8      `json:"fiscal_month"`
	CalendarYear  int16     `json:"calendar_year"`
	CalendarMonth int8      `json:"calendar_month"`
	StartDate     time.Time `json:"start_date"`
	EndDate       time.Time `json:"end_date"`
	Label         string    `json:"label"`
}

func (q *Queries) UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) error {
	_, err := q.db.ExecContext(ctx, upsertPeriod,
		arg.FiscalYear,
		arg.FiscalMonth,
		arg.CalendarYear,
		arg.CalendarMonth,
		arg.StartDate,
		arg.EndDate,
		arg.Label,
	)
	return err
}
