// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CompleteImportBatch(ctx context.Context, arg CompleteImportBatchParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (int64, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (int64, error)
	CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (int64, error)
	CreateInitiative(ctx context.Context, arg CreateInitiativeParams) (int64, error)
	CreateInputBinding(ctx context.Context, arg CreateInputBindingParams) (int64, error)
	CreateInputBindingAxisLabel(ctx context.Context, arg CreateInputBindingAxisLabelParams) error
	CreateInputSheet(ctx context.Context, arg CreateInputSheetParams) (int64, error)
	CreateScenarioVersion(ctx context.Context, arg CreateScenarioVersionParams) (int64, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (int64, error)
	CreateSubmissionScope(ctx context.Context, arg CreateSubmissionScopeParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	// ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id) lets a previously
	// deactivated assignment be reactivated by the same (user, business,
	// department) triple: a plain "SET is_active = TRUE" without the
	// LAST_INSERT_ID(id) trick would make execlastid report 0 instead of the
	// existing row's id.
	CreateUserAssignment(ctx context.Context, arg CreateUserAssignmentParams) (int64, error)
	DeactivateUserAssignment(ctx context.Context, id uint64) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, tokenHash string) error
	GetCurrentScenarioVersion(ctx context.Context, arg GetCurrentScenarioVersionParams) (ScenarioVersion, error)
	GetInputBinding(ctx context.Context, id uint64) (InputBinding, error)
	GetInputSheet(ctx context.Context, id uint64) (InputSheet, error)
	GetScenarioVersionByID(ctx context.Context, id uint64) (ScenarioVersion, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (UserSession, error)
	GetUserByEmail(ctx context.Context, email string) (AppUser, error)
	GetUserByID(ctx context.Context, id uint64) (AppUser, error)
	ListAccounts(ctx context.Context) ([]DimAccount, error)
	ListActiveUserAssignments(ctx context.Context) ([]ListActiveUserAssignmentsRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListAxisLabelsByBinding(ctx context.Context, bindingID uint64) ([]InputBindingAxisLabel, error)
	ListBusinesses(ctx context.Context) ([]DimBusiness, error)
	ListDepartments(ctx context.Context) ([]DimDepartment, error)
	ListFactAmountsByScenarioVersion(ctx context.Context, scenarioVersionID uint64) ([]ListFactAmountsByScenarioVersionRow, error)
	ListImportBatchesByScenarioVersion(ctx context.Context, scenarioVersionID uint64) ([]ImportBatch, error)
	ListInitiatives(ctx context.Context) ([]DimInitiative, error)
	ListInputBindingsBySheet(ctx context.Context, inputSheetID uint64) ([]InputBinding, error)
	ListInputSheetsByOwner(ctx context.Context, ownerUserID uint64) ([]ListInputSheetsByOwnerRow, error)
	ListPeriods(ctx context.Context) ([]DimPeriod, error)
	ListScenarioVersions(ctx context.Context, arg ListScenarioVersionsParams) ([]ScenarioVersion, error)
	ListServices(ctx context.Context) ([]DimService, error)
	// Ordered submitted_at DESC so callers can dedupe by (business_id,
	// department_id) and keep the first row seen — that's the latest
	// non-superseded submission covering that scope.
	ListSubmissionScopesByScenarioVersion(ctx context.Context, scenarioVersionID uint64) ([]ListSubmissionScopesByScenarioVersionRow, error)
	ListSubmissionsBySheet(ctx context.Context, inputSheetID uint64) ([]Submission, error)
	ListSubmissionsForReview(ctx context.Context) ([]ListSubmissionsForReviewRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	LockScenarioVersion(ctx context.Context, id uint64) (int64, error)
	SubmitScenarioVersion(ctx context.Context, id uint64) (int64, error)
	TouchSession(ctx context.Context, tokenHash string) error
	UnsetCurrentScenarioVersions(ctx context.Context, arg UnsetCurrentScenarioVersionsParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) error
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) error
	UpdateInitiative(ctx context.Context, arg UpdateInitiativeParams) error
	UpdateInputSheetSnapshot(ctx context.Context, arg UpdateInputSheetSnapshotParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) error
	UpsertFactAmountFromImport(ctx context.Context, arg UpsertFactAmountFromImportParams) error
	UpsertFactAmountFromSubmission(ctx context.Context, arg UpsertFactAmountFromSubmissionParams) error
	UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) error
}

var _ Querier = (*Queries)(nil)
