// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scenarios.sql

package db

import (
	"context"
	"database/sql"
)

const createScenarioVersion = `-- name: CreateScenarioVersion :execlastid
INSERT INTO scenario_version (scenario_type, fiscal_year, as_of_period_id, version_label, is_current, created_by)
VALUES (?, ?, ?, ?, TRUE, ?)
`

type CreateScenarioVersionParams struct {
	ScenarioType ScenarioVersionScenarioType `json:"scenario_type"`
	FiscalYear   int16                       `json:"fiscal_year"`
	AsOfPeriodID sql.NullInt64               `json:"as_of_period_id"`
	VersionLabel string                      `json:"version_label"`
	CreatedBy    uint64                      `json:"created_by"`
}

func (q *Queries) CreateScenarioVersion(ctx context.Context, arg CreateScenarioVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createScenarioVersion,
		arg.ScenarioType,
		arg.FiscalYear,
		arg.AsOfPeriodID,
		arg.VersionLabel,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getCurrentScenarioVersion = `-- name: GetCurrentScenarioVersion :one
SELECT id, scenario_type, fiscal_year, as_of_period_id, version_label, status, is_current, created_by, created_at, submitted_at, locked_at
FROM scenario_version
WHERE scenario_type = ? AND fiscal_year = ? AND is_current = TRUE
LIMIT 1
`

type GetCurrentScenarioVersionParams struct {
	ScenarioType ScenarioVersionScenarioType `json:"scenario_type"`
	FiscalYear   int16                       `json:"fiscal_year"`
}

func (q *Queries) GetCurrentScenarioVersion(ctx context.Context, arg GetCurrentScenarioVersionParams) (ScenarioVersion, error) {
	row := q.db.QueryRowContext(ctx, getCurrentScenarioVersion, arg.ScenarioType, arg.FiscalYear)
	var i ScenarioVersion
	err := row.Scan(
		&i.ID,
		&i.ScenarioType,
		&i.FiscalYear,
		&i.AsOfPeriodID,
		&i.VersionLabel,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.LockedAt,
	)
	return i, err
}

const listScenarioVersions = `-- name: ListScenarioVersions :many
SELECT id, scenario_type, fiscal_year, as_of_period_id, version_label, status, is_current, created_by, created_at, submitted_at, locked_at
FROM scenario_version
WHERE scenario_type = ? AND fiscal_year = ?
ORDER BY created_at DESC
`

type ListScenarioVersionsParams struct {
	ScenarioType ScenarioVersionScenarioType `json:"scenario_type"`
	FiscalYear   int16                       `json:"fiscal_year"`
}

func (q *Queries) ListScenarioVersions(ctx context.Context, arg ListScenarioVersionsParams) ([]ScenarioVersion, error) {
	rows, err := q.db.QueryContext(ctx, listScenarioVersions, arg.ScenarioType, arg.FiscalYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScenarioVersion
	for rows.Next() {
		var i ScenarioVersion
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioType,
			&i.FiscalYear,
			&i.AsOfPeriodID,
			&i.VersionLabel,
			&i.Status,
			&i.IsCurrent,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.LockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetCurrentScenarioVersions = `-- name: UnsetCurrentScenarioVersions :exec
UPDATE scenario_version
SET is_current = FALSE
WHERE scenario_type = ? AND fiscal_year = ? AND is_current = TRUE
`

type UnsetCurrentScenarioVersionsParams struct {
	ScenarioType ScenarioVersionScenarioType `json:"scenario_type"`
	FiscalYear   int16                       `json:"fiscal_year"`
}

func (q *Queries) UnsetCurrentScenarioVersions(ctx context.Context, arg UnsetCurrentScenarioVersionsParams) error {
	_, err := q.db.ExecContext(ctx, unsetCurrentScenarioVersions, arg.ScenarioType, arg.FiscalYear)
	return err
}
