// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO user_session (token_hash, user_id, expires_at, ip_address, user_agent)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string         `json:"token_hash"`
	UserID    uint64         `json:"user_id"`
	ExpiresAt time.Time      `json:"expires_at"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM user_session
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_session
WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT token_hash, user_id, created_at, expires_at, last_seen_at, ip_address, user_agent
FROM user_session
WHERE token_hash = ? AND expires_at > NOW()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i UserSession
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE user_session
SET last_seen_at = NOW()
WHERE token_hash = ?
`

func (q *Queries) TouchSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, touchSession, tokenHash)
	return err
}
