// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package db

import (
	"context"
	"encoding/json"
)

const createSubmission = `-- name: CreateSubmission :execlastid
INSERT INTO submission (
  input_sheet_id, binding_id, scenario_version_id, submitted_by,
  status, validation_status, validation_detail
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSubmissionParams struct {
	InputSheetID      uint64                     `json:"input_sheet_id"`
	BindingID         uint64                     `json:"binding_id"`
	ScenarioVersionID uint64                     `json:"scenario_version_id"`
	SubmittedBy       uint64                     `json:"submitted_by"`
	Status            SubmissionStatus           `json:"status"`
	ValidationStatus  SubmissionValidationStatus `json:"validation_status"`
	ValidationDetail  json.RawMessage            `json:"validation_detail"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSubmission,
		arg.InputSheetID,
		arg.BindingID,
		arg.ScenarioVersionID,
		arg.SubmittedBy,
		arg.Status,
		arg.ValidationStatus,
		arg.ValidationDetail,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listSubmissionsBySheet = `-- name: ListSubmissionsBySheet :many
SELECT id, input_sheet_id, binding_id, scenario_version_id, submitted_by,
       submitted_at, status, validation_status, validation_detail
FROM submission
WHERE input_sheet_id = ?
ORDER BY submitted_at DESC
`

func (q *Queries) ListSubmissionsBySheet(ctx context.Context, inputSheetID uint64) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsBySheet, inputSheetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.InputSheetID,
			&i.BindingID,
			&i.ScenarioVersionID,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.Status,
			&i.ValidationStatus,
			&i.ValidationDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
