// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_assignments.sql

package db

import (
	"context"
)

const createUserAssignment = `-- name: CreateUserAssignment :execlastid
INSERT INTO user_assignment (user_id, business_id, department_id)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), is_active = TRUE
`

type CreateUserAssignmentParams struct {
	UserID       uint64 `json:"user_id"`
	BusinessID   uint64 `json:"business_id"`
	DepartmentID uint64 `json:"department_id"`
}

// ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id) lets a previously
// deactivated assignment be reactivated by the same (user, business,
// department) triple: a plain "SET is_active = TRUE" without the
// LAST_INSERT_ID(id) trick would make execlastid report 0 instead of the
// existing row's id.
func (q *Queries) CreateUserAssignment(ctx context.Context, arg CreateUserAssignmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createUserAssignment, arg.UserID, arg.BusinessID, arg.DepartmentID)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deactivateUserAssignment = `-- name: DeactivateUserAssignment :exec
UPDATE user_assignment SET is_active = FALSE WHERE id = ?
`

func (q *Queries) DeactivateUserAssignment(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deactivateUserAssignment, id)
	return err
}

const listActiveUserAssignments = `-- name: ListActiveUserAssignments :many
SELECT ua.id, ua.user_id, u.name AS user_name, u.email AS user_email,
       ua.business_id, b.code AS business_code, b.name AS business_name,
       ua.department_id, d.code AS department_code, d.name AS department_name
FROM user_assignment ua
JOIN app_user u ON u.id = ua.user_id
JOIN dim_business b ON b.id = ua.business_id
JOIN dim_department d ON d.id = ua.department_id
WHERE ua.is_active = TRUE
ORDER BY b.code, d.code, u.name
`

type ListActiveUserAssignmentsRow struct {
	ID             uint64 `json:"id"`
	UserID         uint64 `json:"user_id"`
	UserName       string `json:"user_name"`
	UserEmail      string `json:"user_email"`
	BusinessID     uint64 `json:"business_id"`
	BusinessCode   string `json:"business_code"`
	BusinessName   string `json:"business_name"`
	DepartmentID   uint64 `json:"department_id"`
	DepartmentCode string `json:"department_code"`
	DepartmentName string `json:"department_name"`
}

func (q *Queries) ListActiveUserAssignments(ctx context.Context) ([]ListActiveUserAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUserAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUserAssignmentsRow
	for rows.Next() {
		var i ListActiveUserAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.BusinessID,
			&i.BusinessCode,
			&i.BusinessName,
			&i.DepartmentID,
			&i.DepartmentCode,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
